/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { IMOCK1155 } from "./IMOCK1155";
export type { IMOCK20 } from "./IMOCK20";
export type { IMOCK721 } from "./IMOCK721";
