/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import type { Provider } from "@ethersproject/providers";
import type {
  IMOCK721,
  IMOCK721Interface,
} from "../../../../contracts/interfaces/IMOCK721.sol/IMOCK721";

const _abi = [
  {
    inputs: [
      {
        internalType: "address",
        name: "to",
        type: "address",
      },
    ],
    name: "safeMint",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
] as const;

export class IMOCK721__factory {
  static readonly abi = _abi;
  static createInterface(): IMOCK721Interface {
    return new utils.Interface(_abi) as IMOCK721Interface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): IMOCK721 {
    return new Contract(address, _abi, signerOrProvider) as IMOCK721;
  }
}
