/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { IMOCK721__factory } from "./IMOCK721__factory";
export { IMockERC721__factory } from "./IMockERC721__factory";
