/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { GameBaseNFT__factory } from "./GameBaseNFT__factory";
export { IERC6551Registry__factory } from "./IERC6551Registry__factory";
