/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { GameBaseNFT__factory } from "./GameBaseNFT__factory";
export { MockERC721__factory } from "./MockERC721__factory";
