/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { IERC4906 } from "./IERC4906";
export type { IERC4907 } from "./IERC4907";
export type { IERC6551Registry } from "./IERC6551Registry";
