/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { GameBaseNFT } from "./GameBaseNFT";
export type { IERC6551Registry } from "./IERC6551Registry";
