/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as gameBaseNftSol from "./GameBaseNFT.sol";
export type { gameBaseNftSol };
import type * as interfaces from "./interfaces";
export type { interfaces };
